# MiningRewards Configuration

# Chance of a diamond being dropped when breaking naturally spawning ores
# you can use any number between 0 and 1 where 0 is 0% and 1 is 100%, below are some examples
# 0.01 = 1% chance
# 0.05 = 5% chance
# 0.1 = 10% chance
# 0.25 = 25% chance
# 0.5 = 50% chance
# 0.75 = 75% chance
# 1 = 100% chance
diamond_chance: 0.05

# List of blocks that will drop the reward (does not have to be ores)
# Please use this list to find the correct material name: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
ores:
  - COAL_ORE
  - IRON_ORE
  - COPPER_ORE
  - GOLD_ORE
  - LAPIS_ORE
  - REDSTONE_ORE
  - DIAMOND_ORE
  - EMERALD_ORE
  - NETHER_QUARTZ_ORE
  - NETHER_GOLD_ORE
  - ANCIENT_DEBRIS
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_COPPER_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_EMERALD_ORE

# List of rewards to randomly choose from in the format "reward:quantity"
# Please use this list to find the correct material name: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
rewards:
  - DIAMOND:1
  - EMERALD:1
  - APPLE:3